---
- name: Deploy to Kubernetes
  hosts: all
  gather_facts: false

  environment:
    KUBECONFIG: /var/jenkins_home/.kube/config

  tasks:
    - name: Apply Deployment
      ansible.builtin.shell: kubectl apply -f ../deployment.yaml

    - name: Apply Service
      ansible.builtin.shell: kubectl apply -f ../service.yaml